### ISSUE TITLE
Failed to clear dstein64/nvim-scrollview from buffer at once after running Bdelete

### ISSUE THREAD

**Issue by Julpikar** [famiu/bufdelete.nvim#3] opened 2021-07-17 03:29 UTC
The buffer used by [dstein64/nvim-scrollview](https://github.com/dstein64/nvim-scrollview) cannot be deleted at once since the most recent commit after 1d06b37d090ca15c7adb35ec21eaef36d88e0e9b.
### How to reproduce
- open 2 different file.
- In an open file buffer, run the Bdelete command.
- Scrollview buffer of the first file will appear instead of the second file buffer (check with the command :set filetype?).

**Comment by famiu** [comment] 2021-07-17 05:42
It's probably an issue with nvim-scrollview and not bufdelete

**Comment by Julpikar** [comment] 2021-07-17 14:07
Ok thanks

**Comment by famiu** [comment] 2021-07-17 15:15
I'm closing this issue. Feel free to reopen it if you're sure the issue is not caused by nvim-scrollview

**Closed by famiu** 2021-07-17 15:15 UTC
