### ISSUE TITLE
A strange delay when closing a buffer

### ISSUE THREAD

**Issue by lcfd** [famiu/bufdelete.nvim#21] opened 2022-10-03 13:27 UTC
Hi! 

Maybe it's only me but I'm experiencing a strange delay when I delete a buffer.
The usual `:bdelete` is much faster.

I run the command using a keystroke:

```lua
vim.keymap.set("n", "<leader>c", "<cmd>Bdelete<cr>")
```

Is it correct?

**Comment by famiu** [comment] 2022-10-03 14:10
Yes, a slight delay is expected since Bdelete has to do more processing prior to invoking `:bdelete` but it shouldn't even be noticable. It's weird that you're seeing a delay. Do you have a lot of buffers open? Maybe a plugin is causing a lot of hidden buffers to be opened?

**Comment by lcfd** [comment] 2022-10-03 19:37
I'll do some tests! Maybe with some usage I'll discover more.

Thank you for your time!

**Comment by famiu** [comment] 2022-10-04 17:23
BTW, until we can find some concrete benchmarks that are consistently reproducible, I'm going to be closing this issue. Feel free to reopen if you can provide that.

**Closed by famiu** 2022-10-04 17:23 UTC

**Comment by erodactyl** [comment] 2023-06-09 19:46
@lcfd I had the same issue, turns out I had a keymap <leader>ca for code actions so it was waiting to see if I also click "a". Removing that keymap fixed the delay it's super fast now.
